add_subdirectory(ch01_foundations)
add_subdirectory(ch02_backends)
add_subdirectory(ch03_tokenization)
add_subdirectory(ch04_dataset)
add_subdirectory(ch05_autograd)
add_subdirectory(ch06_embeddings)
add_subdirectory(ch07_attention)
add_subdirectory(ch08_gpt)
add_subdirectory(ch09_optimizer)
add_subdirectory(ch10_modern_arch)
add_subdirectory(ch11_pretraining)
add_subdirectory(ch12_finetuning)
add_subdirectory(ch13_alignment)
add_subdirectory(ch14_inference)
add_subdirectory(ch15_distillation)
add_subdirectory(ch16_thinking)
add_subdirectory(ch17_looped_gpt)
add_subdirectory(ch18_moe)
add_subdirectory(ch19_mtp)
add_subdirectory(ch20_rlhf)
add_subdirectory(ch21_math_neurons)
add_subdirectory(ch22_math_lm)
add_subdirectory(ch23_reasoned_math)
# Chapters are added here as they are written.
