// sub0diff-specialize — the diffusion track's compile-time specialization front-end.
//
// Ch28 scope (this tool, today): the HOST axis. It detects the build machine's fixed
// hardware facts (logical/physical cores, performance- vs efficiency-core split, total
// RAM, L1 line size, widest SIMD) and emits a `<name>_host_spec.hpp` whose every field is
// a `static constexpr` member of a generated struct meeting sub0diff::HostSpec. A
// specialized diffusion binary includes that header, sizes its thread pools / tiling
// against the constants, and calls verify_host<Spec>() in its `--verify` mode to assert
// the running machine still matches (warn on benign drift, abort on a SIGILL-class gap).
//
// (The model-shape axis — a generated DiffusionStaticSpec from a GGUF — lands with the
//  real-model engine in Ch32; the educational chapters build small models at runtime.)
//
// Usage:
//   sub0diff-specialize --detect                         print live host facts
//   sub0diff-specialize --emit-host-spec [--name Host]   write <name>_host_spec.hpp
//                       [--out-dir DIR] [--namespace NS]

#include "sub0diff/spec/host_spec.hpp"

#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>

namespace {

std::string sanitize_ident(std::string s) {
    for (char& c : s)
        if (!std::isalnum(static_cast<unsigned char>(c))) c = '_';
    if (!s.empty() && std::isdigit(static_cast<unsigned char>(s.front())))
        s.insert(s.begin(), '_');
    return s;
}

void print_facts(const sub0diff::HostFacts& f) {
    std::cout << "\n  live host facts\n";
    std::cout << "  ----------------------------------------------------------\n";
    std::cout << std::format("    cpu              {}\n", f.cpu_brand.empty() ? "(unknown)" : f.cpu_brand);
    std::cout << std::format("    logical cores    {}\n", f.logical_cores);
    std::cout << std::format("    physical cores   {}\n", f.physical_cores);
    std::cout << std::format("    P / E cores      {} / {}\n", f.perf_cores, f.eff_cores);
    std::cout << std::format("    RAM              {:.2f} GiB ({} bytes)\n",
                             static_cast<double>(f.ram_bytes) / (1024.0 * 1024.0 * 1024.0), f.ram_bytes);
    std::cout << std::format("    L1 line          {} bytes\n", f.cacheline_bytes);
    std::cout << std::format("    SIMD width       {} bits\n", f.simd_width_bits);
    std::cout << "  ----------------------------------------------------------\n";
}

void emit_host_spec(std::ostream& out, const sub0diff::HostFacts& f,
                    const std::string& ident, const std::string& ns) {
    out << "// AUTO-GENERATED by sub0diff-specialize — DO NOT EDIT.\n";
    out << "// Host: " << (f.cpu_brand.empty() ? "(unknown)" : f.cpu_brand) << "\n";
    out << "//\n";
    out << "// Every field is a compile-time constant describing the build host. Include this\n";
    out << "// header in a specialized diffusion binary and call sub0diff::verify_host<" << ident << ">()\n";
    out << "// (e.g. behind a --verify flag) to confirm the running machine still matches.\n";
    out << "#pragma once\n\n";
    out << "#include \"sub0diff/spec/host_spec.hpp\"\n\n";
    out << "#include <cstdint>\n\n";
    out << "namespace " << ns << " {\n\n";
    out << "struct " << ident << " {\n";
    out << std::format("    static constexpr unsigned      logical_cores   = {};\n", f.logical_cores);
    out << std::format("    static constexpr unsigned      physical_cores  = {};\n", f.physical_cores);
    out << std::format("    static constexpr unsigned      perf_cores      = {};\n", f.perf_cores);
    out << std::format("    static constexpr unsigned      eff_cores       = {};\n", f.eff_cores);
    out << std::format("    static constexpr std::uint64_t ram_bytes       = {}ull;\n", f.ram_bytes);
    out << std::format("    static constexpr unsigned      cacheline_bytes = {};\n", f.cacheline_bytes);
    out << std::format("    static constexpr unsigned      simd_width_bits = {};\n", f.simd_width_bits);
    out << "};\n\n";
    out << "static_assert(sub0diff::HostSpec<" << ident << ">,\n";
    out << "              \"generated host spec must satisfy the HostSpec concept\");\n\n";
    out << "} // namespace " << ns << "\n";
}

} // namespace

int main(int argc, char** argv) {
    bool detect = false, emit = false;
    std::string name = "Host", out_dir = ".", ns = "sub0diff::spec";

    for (int i = 1; i < argc; ++i) {
        std::string_view a = argv[i];
        auto next = [&]() -> std::string {
            if (i + 1 >= argc) throw std::runtime_error(std::format("missing value for {}", a));
            return argv[++i];
        };
        if (a == "--detect")              detect  = true;
        else if (a == "--emit-host-spec") emit    = true;
        else if (a == "--name")           name    = next();
        else if (a == "--out-dir")        out_dir = next();
        else if (a == "--namespace")      ns      = next();
        else if (a == "-h" || a == "--help") {
            std::cout << "usage: sub0diff-specialize [--detect] [--emit-host-spec "
                         "--name N --out-dir DIR --namespace NS]\n";
            return 0;
        } else {
            std::cerr << "unknown argument: " << a << "\n";
            return 2;
        }
    }

    if (!detect && !emit) detect = true;  // default: just show the host

    try {
        const sub0diff::HostFacts facts = sub0diff::detect_host();
        if (detect) print_facts(facts);

        if (emit) {
            namespace fs = std::filesystem;
            const std::string ident = sanitize_ident(name);
            std::string lower_ident = ident;
            for (char& c : lower_ident) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
            fs::create_directories(out_dir);
            const fs::path hdr = fs::path(out_dir) / (lower_ident + "_host_spec.hpp");
            std::ofstream fout(hdr);
            if (!fout) throw std::runtime_error(std::format("cannot write {}", hdr.string()));
            emit_host_spec(fout, facts, ident, ns);
            std::cout << "  wrote " << hdr.string() << "\n";
            std::cout << "  next: include \"" << lower_ident << "_host_spec.hpp\" and call "
                         "sub0diff::verify_host<" << ns << "::" << ident << ">(sub0diff::detect_host())\n";
        }
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "[sub0diff-specialize] error: " << e.what() << "\n";
        return 1;
    }
}
