// configurator.cpp — stage 1 of the build chain ("sub0-configure").
//
// This tool is intentionally INDEPENDENT of the engine: it is the program that
// *produces* the compile-time configuration the engine is built against, so it
// cannot itself depend on that configuration. It takes the model dimensions
// (passed through from CMake cache variables / runtime arguments) plus the
// training corpus, derives the vocabulary from the corpus, and writes a
// generated header full of constexpr constants. Downstream stages compile
// against that header, baking the configuration into the binaries.
//
// Usage:
//   sub0-configure --corpus <path> --dmodel N --layers N --heads N --seq N
//                  --ternary 0|1 -o <generated_config.hpp>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iterator>
#include <set>
#include <string>
#include <vector>

static const char* arg_str(int c, char** v, const char* k, const char* d) {
    for (int i = 1; i < c - 1; ++i) if (!std::strcmp(v[i], k)) return v[i + 1];
    return d;
}
static int arg_int(int c, char** v, const char* k, int d) {
    for (int i = 1; i < c - 1; ++i) if (!std::strcmp(v[i], k)) return std::atoi(v[i + 1]);
    return d;
}

int main(int argc, char** argv) {
    const char* corpus = arg_str(argc, argv, "--corpus", nullptr);
    const char* out    = arg_str(argc, argv, "-o", nullptr);
    int d_model  = arg_int(argc, argv, "--dmodel", 96);
    int n_layers = arg_int(argc, argv, "--layers", 3);
    int n_heads  = arg_int(argc, argv, "--heads", 4);
    int seq_len  = arg_int(argc, argv, "--seq", 64);
    int ternary  = arg_int(argc, argv, "--ternary", 0);

    if (!corpus || !out) {
        std::fprintf(stderr, "usage: sub0-configure --corpus <path> -o <header> "
                             "[--dmodel N --layers N --heads N --seq N --ternary 0|1]\n");
        return 1;
    }
    if (d_model % n_heads != 0) {
        std::fprintf(stderr, "configure error: dmodel (%d) not divisible by heads (%d)\n",
                     d_model, n_heads);
        return 1;
    }

    // Read the corpus and derive the vocabulary: the sorted set of distinct bytes.
    std::ifstream is(corpus, std::ios::binary);
    if (!is) { std::fprintf(stderr, "configure error: cannot read corpus '%s'\n", corpus); return 1; }
    std::string text((std::istreambuf_iterator<char>(is)), std::istreambuf_iterator<char>());
    std::set<unsigned char> seen;
    for (unsigned char ch : text) seen.insert(ch);
    if (seen.empty()) { std::fprintf(stderr, "configure error: empty corpus\n"); return 1; }
    std::vector<unsigned char> vocab(seen.begin(), seen.end());  // ascending byte order

    // Resolve an absolute corpus path so the trainer finds it regardless of cwd.
    std::string abspath = corpus;
    {
        char buf[4096];
        if (corpus[0] != '/' && realpath(corpus, buf)) abspath = buf;
        else if (corpus[0] == '/') abspath = corpus;
    }

    std::ofstream os(out, std::ios::binary);
    if (!os) { std::fprintf(stderr, "configure error: cannot write '%s'\n", out); return 1; }

    auto emit_char = [&](unsigned char c) {
        // Emit a char literal safely for the generated source.
        switch (c) {
            case '\n': os << "'\\n'"; break;
            case '\t': os << "'\\t'"; break;
            case '\r': os << "'\\r'"; break;
            case '\\': os << "'\\\\'"; break;
            case '\'': os << "'\\''"; break;
            default:
                if (c >= 32 && c < 127) os << "'" << (char)c << "'";
                else { char b[16]; std::snprintf(b, sizeof b, "(char)%d", (int)c); os << b; }
        }
    };

    os << "// AUTO-GENERATED by sub0-configure. Do not edit.\n";
    os << "// Vocabulary and dimensions are baked in at build time.\n";
    os << "#pragma once\n\n";
    os << "constexpr int  D_MODEL     = " << d_model  << ";\n";
    os << "constexpr int  N_LAYERS    = " << n_layers << ";\n";
    os << "constexpr int  N_HEADS     = " << n_heads  << ";\n";
    os << "constexpr int  SEQ_LEN     = " << seq_len  << ";\n";
    os << "constexpr int  D_FF        = 4 * D_MODEL;\n";
    os << "constexpr int  D_HEAD      = D_MODEL / N_HEADS;\n";
    os << "constexpr bool USE_TERNARY = " << (ternary ? "true" : "false") << ";\n";
    os << "constexpr int  VOCAB       = " << vocab.size() << ";\n\n";

    // id -> char
    os << "inline constexpr char VOCAB_CHARS[VOCAB] = {";
    for (size_t i = 0; i < vocab.size(); ++i) { if (i) os << ", "; emit_char(vocab[i]); }
    os << "};\n\n";

    // byte -> id (-1 if not in vocab)
    int byte_to_id[256];
    for (int i = 0; i < 256; ++i) byte_to_id[i] = -1;
    for (size_t i = 0; i < vocab.size(); ++i) byte_to_id[vocab[i]] = (int)i;
    os << "inline constexpr int VOCAB_ID[256] = {";
    for (int i = 0; i < 256; ++i) { if (i) os << ((i % 16) ? ", " : ",\n  "); os << byte_to_id[i]; }
    os << "};\n\n";

    // Default corpus path, so the trainer can default to the configured corpus.
    os << "inline constexpr char DEFAULT_CORPUS[] = \"";
    for (char c : abspath) { if (c == '\\' || c == '"') os << '\\'; os << c; }
    os << "\";\n";

    std::printf("sub0-configure: vocab=%zu chars, d=%d L=%d H=%d seq=%d%s -> %s\n",
                vocab.size(), d_model, n_layers, n_heads, seq_len,
                ternary ? " (ternary)" : "", out);
    return 0;
}
