// engine_core.cpp — backend-agnostic part of the engine core (part of libsub0_core).
//
// Holds everything that does NOT depend on how the math is executed: model
// serialization (the checkpoint header + the flat parameter blob), the runtime BPE
// tokenizer, the logits sampler, and the baked-in artifact paths. The differentiable
// compute (forward / backward / train_batch / AdamW) and the parameter arenas live
// in a compute backend translation unit (backend_cpu.cpp today; a CUDA backend
// later). This file reaches the parameters only through the backend's public
// accessors — params_ptr() / trainable_floats() — bracketed by the host/device
// sync hooks, so the same serialization works whether the live weights are in host
// memory (CPU) or device memory (GPU).

#include "sub0/core.hpp"
#include "sub0/casing.hpp"
#include "sub0/tokenizer.hpp"
#include "sub0/layout.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <limits>
#include <print>
#include <random>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace sub0 {

// ============================================================================
//  Serialization (header validates the generated config)
// ============================================================================
// The on-disk format is one backend-agnostic blob: a Header that pins the constexpr
// config, then PARAM_FLOATS floats in PARAM_LAYOUT order. Reading/writing goes
// through params_ptr() so a device backend can stage the weights via the sync hooks
// without changing the file format.

namespace {
struct Header {
    char magic[4] = {'S', '0', 'L', '5'};
    int d_model = D_MODEL, n_layers = N_LAYERS, n_heads = N_HEADS;
    int d_ff = D_FF, seq_len = SEQ_LEN, vocab = VOCAB, ternary = USE_TERNARY;
    int pos_encoding = static_cast<int>(POS_ENCODING);   // 0 = absolute learned, 1 = RoPE
    uint64_t param_floats = PARAM_FLOATS;
};

// The runtime tokenizer state (loaded from tokenizer.tok). Loading, encoding and detokenizing all
// delegate to the shared sub0::tok library (src/tokenizer.cpp) -- the single definition the build-time
// configurator uses too, so prompts encode byte-identically to how the corpus was tokenized at build.
tok::Tokenizer g_tok;

// Tokenizer fingerprint stamped in the last model loaded (0 = unknown: a legacy model without the
// trailer, or no model loaded). A trained model is only meaningful decoded by the vocab it was trained
// against; this pins that identity so a mismatched decoder fails loudly rather than emitting garble.
std::uint64_t g_model_tok_fp = 0;

// True iff BOTH a model and a tokenizer are loaded with KNOWN fingerprints that disagree -- i.e. the
// decoder does not match the vocab the weights were trained with. Whichever of load_model /
// load_tokenizer completes the pair second calls this, so the order does not matter.
bool tok_model_conflict() {
    return g_model_tok_fp != 0 && g_tok.loaded && tok::fingerprint(g_tok) != g_model_tok_fp;
}

// A shared, actionable message for the mismatch (both load paths print it).
void warn_tok_model_mismatch() {
    std::println(stderr,
        "error: tokenizer does not match the vocabulary this model was trained with "
        "(fingerprint {:#018x} != {:#018x}).\n"
        "       Decoding would produce garble. This usually means the build's tokenizer.tok was "
        "regenerated by a later `configure` for a different corpus.\n"
        "       Fix: use the tokenizer.tok bundled in the model's directory, or re-run `configure` "
        "on the SAME corpus this model was trained on to regenerate the matching vocab.",
        tok::fingerprint(g_tok), g_model_tok_fp);
}
}

void save_model(const char* path) {
    sync_params_to_host();                       // pull live weights into the host staging buffer
    std::ofstream os(path, std::ios::binary);
    Header h;
    os.write((const char*)&h, sizeof(h));
    os.write((const char*)params_ptr(), (std::streamsize)(PARAM_FLOATS * sizeof(float)));
    // Trailing 8-byte tokenizer fingerprint: stamps WHICH vocab these weights were trained against so a
    // mismatched decoder is caught on load (0 when no tokenizer is loaded). Appended after the params so
    // a legacy reader that stops at PARAM_FLOATS is unaffected -- and a legacy file (no trailer) simply
    // reads back as fingerprint 0 (unknown), i.e. no guard. No format-magic bump needed.
    const std::uint64_t fp = g_tok.loaded ? tok::fingerprint(g_tok) : 0;
    os.write((const char*)&fp, sizeof(fp));
}

bool load_model(const char* path) {
    std::ifstream is(path, std::ios::binary);
    if (!is) return false;
    Header h, ref;
    is.read((char*)&h, sizeof(h));
    if (std::memcmp(h.magic, ref.magic, 4) != 0 ||
        h.d_model != ref.d_model || h.n_layers != ref.n_layers || h.n_heads != ref.n_heads ||
        h.d_ff != ref.d_ff || h.seq_len != ref.seq_len || h.vocab != ref.vocab ||
        h.ternary != ref.ternary || h.pos_encoding != ref.pos_encoding ||
        h.param_floats != ref.param_floats) {
        std::println(stderr, "error: model was built with a different (constexpr) config");
        return false;
    }
    is.read((char*)params_ptr(), (std::streamsize)(PARAM_FLOATS * sizeof(float)));
    if (!is) return false;
    sync_params_to_device();                     // push the loaded weights to the live (device) copy
    // Optional trailing tokenizer fingerprint (see save_model). A legacy model has none -> read fails
    // and leaves the fingerprint unknown (0 = no guard). If a tokenizer is already loaded, catch a
    // mismatch now (covers the load-tokenizer-then-load-model order; gen does the reverse).
    std::uint64_t fp = 0;
    is.read((char*)&fp, sizeof(fp));
    g_model_tok_fp = (is.gcount() == static_cast<std::streamsize>(sizeof(fp))) ? fp : 0;
    if (tok_model_conflict()) { warn_tok_model_mismatch(); return false; }
    return true;
}

const char* default_corpus()     { return DEFAULT_CORPUS; }
const char* default_corpus_tok() { return DEFAULT_CORPUS_TOK; }
const char* default_tokenizer()  { return DEFAULT_TOKENIZER; }

// ============================================================================
//  Runtime BPE tokenizer (loaded from tokenizer.tok) -- state declared up top
//  (g_tok) so save_model/load_model can fingerprint-guard the decoder/model pair.
// ============================================================================

std::uint64_t tokenizer_fingerprint() { return g_tok.loaded ? tok::fingerprint(g_tok) : 0; }

bool load_tokenizer(const char* path) {
    std::ifstream is(path, std::ios::binary);
    if (!is) { std::println(stderr, "tokenizer: cannot open '{}'", path); return false; }
    tok::Tokenizer t;
    if (!tok::deserialize(t, is)) { std::println(stderr, "tokenizer: bad or truncated '{}'", path); return false; }
    if (t.vocab != VOCAB)
        std::println(stderr, "tokenizer: vocab {} != built-in VOCAB {} (stale artifact?)", t.vocab, VOCAB);
    g_tok = std::move(t);
    // If a model is already loaded (gen loads the model first, then the tokenizer), refuse a decoder
    // that does not match the vocab those weights were trained against -- a loud, actionable failure
    // instead of silently detokenizing to garble.
    if (tok_model_conflict()) { warn_tok_model_mismatch(); g_tok = {}; return false; }
    return true;
}

std::vector<int> encode(const std::string& text) { return tok::encode(g_tok, text); }

std::string detokenize(const std::vector<int>& ids) { return tok::detokenize(g_tok, ids); }

namespace {
// Render a token's expansion (base-symbol codes) into a printable string: case
// markers become <|cap|>/<|up|>, control and high bytes are escaped, so the table
// stays one line per token regardless of the bytes a merge happens to contain.
std::string render_expansion(const std::vector<int>& codes) {
    std::string s;
    for (int code : codes) {
        if (code == casing::TOK_CAP)      { s += "<|cap|>"; continue; }
        if (code == casing::TOK_UP)       { s += "<|up|>";  continue; }
        const unsigned char c = static_cast<unsigned char>(code);
        switch (c) {
            case '\n': s += "\\n"; break;
            case '\t': s += "\\t"; break;
            case '\r': s += "\\r"; break;
            default:
                if (c >= 0x20 && c < 0x7F) s += static_cast<char>(c);
                else { char b[5]; std::snprintf(b, sizeof b, "\\x%02X", c); s += b; }
        }
    }
    return s;
}
}  // namespace

std::vector<TokenEntry> vocab_entries() {
    std::vector<TokenEntry> rows;
    if (!g_tok.loaded) return rows;
    rows.reserve(g_tok.expansion.size());
    for (std::size_t id = 0; id < g_tok.expansion.size(); ++id) {
        const std::vector<int>& exp = g_tok.expansion[id];
        TokenEntry e;
        e.id = static_cast<int>(id);
        if (static_cast<int>(id) >= g_tok.n_base)        e.kind = TokenEntry::Kind::Merge;
        else if (!exp.empty() && exp[0] == casing::TOK_CAP) e.kind = TokenEntry::Kind::CapMarker;
        else if (!exp.empty() && exp[0] == casing::TOK_UP)  e.kind = TokenEntry::Kind::UpMarker;
        else                                                e.kind = TokenEntry::Kind::Byte;
        e.expansion_len = static_cast<int>(exp.size());
        e.text = render_expansion(exp);
        rows.push_back(std::move(e));
    }
    return rows;
}

int sample_token(const float* logits, float temp, int topk, std::mt19937& rng) {
    std::array<float, VOCAB> l;
    const float invT = 1.f / std::max(1e-6f, temp);
    for (int j = 0; j < VOCAB; ++j) l[j] = logits[j] * invT;
    if (topk > 0 && topk < VOCAB) {                       // keep only the top-k logits
        std::array<int, VOCAB> idx;
        for (int j = 0; j < VOCAB; ++j) idx[j] = j;
        std::partial_sort(idx.begin(), idx.begin() + topk, idx.end(),
                          [&](int a, int b) { return l[a] > l[b]; });
        std::array<float, VOCAB> keep;
        keep.fill(-1e30f);
        for (int t = 0; t < topk; ++t) keep[idx[t]] = l[idx[t]];
        l = keep;
    }
    float mx = -1e30f;
    for (float x : l) mx = std::max(mx, x);
    float Z = 0.f;
    for (float& x : l) { x = std::exp(x - mx); Z += x; }  // softmax (unnormalized; scale r by Z)
    std::uniform_real_distribution<float> ud(0.f, 1.f);
    float r = ud(rng) * Z, acc = 0.f;
    for (int j = 0; j < VOCAB; ++j) { acc += l[j]; if (r <= acc) return j; }
    return VOCAB - 1;
}

}  // namespace sub0
