// engine_core.cpp — backend-agnostic part of the engine core (part of libsub0_core).
//
// Holds everything that does NOT depend on how the math is executed: model
// serialization (the checkpoint header + the flat parameter blob), the runtime BPE
// tokenizer, the logits sampler, and the baked-in artifact paths. The differentiable
// compute (forward / backward / train_batch / AdamW) and the parameter arenas live
// in a compute backend translation unit (backend_cpu.cpp today; a CUDA backend
// later). This file reaches the parameters only through the backend's public
// accessors — params_ptr() / trainable_floats() — bracketed by the host/device
// sync hooks, so the same serialization works whether the live weights are in host
// memory (CPU) or device memory (GPU).

#include "sub0/core.hpp"
#include "sub0/casing.hpp"
#include "sub0/tokenizer.hpp"
#include "sub0/layout.hpp"
#include "sub0/model_file.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <limits>
#include <print>
#include <random>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace sub0 {

// ============================================================================
//  Serialization (header validates the generated config)
// ============================================================================
// The on-disk format is one backend-agnostic blob: a Header that pins the constexpr
// config, then PARAM_FLOATS floats in PARAM_LAYOUT order. Reading/writing goes
// through params_ptr() so a device backend can stage the weights via the sync hooks
// without changing the file format.

namespace {
// The Header struct itself now lives in include/sub0/model_file.hpp as sub0::ModelHeader, because
// WP4c's offline transplant tool is a SECOND writer of this format and is compiled against a
// different config header, so it cannot link the engine (see that file's own comment, and AGENTS.md
// S3 on why two definitions of a fixed-size binary format is the wrong shape). `Header` stays as a
// local alias so every use site below reads exactly as it always did.
using Header = ModelHeader;

// The runtime tokenizer state (loaded from tokenizer.tok). Loading, encoding and detokenizing all
// delegate to the shared sub0::tok library (src/tokenizer.cpp) -- the single definition the build-time
// configurator uses too, so prompts encode byte-identically to how the corpus was tokenized at build.
tok::Tokenizer g_tok;

// Tokenizer fingerprint stamped in the last model loaded (0 = unknown: a legacy model without the
// trailer, or no model loaded). A trained model is only meaningful decoded by the vocab it was trained
// against; this pins that identity so a mismatched decoder fails loudly rather than emitting garble.
std::uint64_t g_model_tok_fp = 0;

// True iff BOTH a model and a tokenizer are loaded with KNOWN fingerprints that disagree -- i.e. the
// decoder does not match the vocab the weights were trained with. Whichever of load_model /
// load_tokenizer completes the pair second calls this, so the order does not matter.
bool tok_model_conflict() {
    return g_model_tok_fp != 0 && g_tok.loaded && tok::fingerprint(g_tok) != g_model_tok_fp;
}

// A shared, actionable message for the mismatch (both load paths print it).
void warn_tok_model_mismatch() {
    std::println(stderr,
        "error: tokenizer does not match the vocabulary this model was trained with "
        "(fingerprint {:#018x} != {:#018x}).\n"
        "       Decoding would produce garble. This usually means the build's tokenizer.tok was "
        "regenerated by a later `configure` for a different corpus.\n"
        "       Fix: use the tokenizer.tok bundled in the model's directory, or re-run `configure` "
        "on the SAME corpus this model was trained on to regenerate the matching vocab.",
        tok::fingerprint(g_tok), g_model_tok_fp);
}
}

bool save_model(const char* path) {
    sync_params_to_host();                       // pull live weights into the host staging buffer
    std::ofstream os(path, std::ios::binary);
    if (!os) return false;                        // e.g. transient lock/permission error
    Header h;
    os.write((const char*)&h, sizeof(h));
    os.write((const char*)params_ptr(), (std::streamsize)(PARAM_FLOATS * sizeof(float)));
    // Trailing 8-byte tokenizer fingerprint: stamps WHICH vocab these weights were trained against so a
    // mismatched decoder is caught on load (0 when no tokenizer is loaded). Appended after the params so
    // a legacy reader that stops at PARAM_FLOATS is unaffected -- and a legacy file (no trailer) simply
    // reads back as fingerprint 0 (unknown), i.e. no guard. No format-magic bump needed.
    const std::uint64_t fp = g_tok.loaded ? tok::fingerprint(g_tok) : 0;
    os.write((const char*)&fp, sizeof(fp));
    // Second trailing record, same additive discipline: the EXECUTION SCHEDULE id (layout.hpp's
    // ARCH_FINGERPRINT): every axis that changes what the model COMPUTES while leaving PARAM_FLOATS and
    // the Header alone -- LoopSplit's schedule and ROPE_THETA today. Nothing else in this file can tell
    // those apart, and the weights are meaningless under the wrong one. Appended after the tokenizer
    // fingerprint so a reader of either older vintage is unaffected.
    const std::uint64_t arch = ARCH_FINGERPRINT;
    os.write((const char*)&arch, sizeof(arch));
    // Third trailing record, same additive discipline: the SECOND architecture fingerprint word
    // (layout.hpp's ARCH_FINGERPRINT2 -- currently only Gated DeltaNet's stride, always 0 today; see
    // docs/GATED_DELTANET.md). Appended after ARCH_FINGERPRINT so a reader built before this field
    // existed simply stops reading one record earlier, unaffected -- and a file written before this
    // field existed reads back below as "no trailer", which load_model treats as 0 (no GDN), the only
    // architecture that has ever actually existed, not a guess the way ARCH_FINGERPRINT_LEGACY's
    // "un-looped" inference had to be.
    const std::uint64_t arch2 = ARCH_FINGERPRINT2;
    os.write((const char*)&arch2, sizeof(arch2));
    return os.good();
}

bool load_model(const char* path) {
    std::ifstream is(path, std::ios::binary);
    if (!is) return false;
    Header h, ref;
    is.read((char*)&h, sizeof(h));
    // seq_len is deliberately NOT compared under RoPE. With no pos_emb table (layout.hpp's
    // HAS_POS_EMB) no parameter tensor's shape depends on the window, so a model trained at one
    // seq_len is bit-compatible with a binary built for a larger one -- which is the entire point of
    // dropping the table, and what makes long-context inference from a short-context checkpoint
    // possible. param_floats still guards every shape that DOES matter, so a genuinely incompatible
    // file is still rejected; under Absolute the table is real and seq_len must match exactly.
    const bool seq_ok = HAS_POS_EMB ? (h.seq_len == ref.seq_len) : true;
    // Accepting a SHORTER trained window is the point of dropping pos_emb, but "accepted" is not
    // "trained for": RoPE positions past h.seq_len were never seen, so quality degrades with no other
    // signal. Say so once, and name the mitigation rather than leaving the reader to find it.
    if (!HAS_POS_EMB && h.seq_len < ref.seq_len)
        std::println(stderr,
            "note: model was trained at seq_len {} but this build's window is {}; positions beyond {} "
            "are extrapolated. --rope-scaling linear (currently {}) is the intended mitigation.",
            h.seq_len, ref.seq_len, h.seq_len,
            ROPE_SCALING_MODE == RopeScaling::None ? "off" : "on");
    if (std::memcmp(h.magic, ref.magic, 4) != 0 ||
        h.d_model != ref.d_model || h.n_layers != ref.n_layers || h.n_heads != ref.n_heads ||
        h.d_ff != ref.d_ff || !seq_ok || h.vocab != ref.vocab ||
        h.ternary != ref.ternary || h.pos_encoding != ref.pos_encoding ||
        h.param_floats != ref.param_floats) {
        std::println(stderr, "error: model was built with a different (constexpr) config");
        return false;
    }
    is.read((char*)params_ptr(), (std::streamsize)(PARAM_FLOATS * sizeof(float)));
    if (!is) return false;
    sync_params_to_device();                     // push the loaded weights to the live (device) copy
    // Trailing tokenizer fingerprint (see save_model) -- REQUIRED. The "absent means unknown, no
    // guard" path is gone with the rest of the legacy-format support: every model this build can load
    // was written by a build that emits it, so a short read means a truncated or foreign file, which is
    // a hard error rather than a reason to silently disable a correctness check.
    std::uint64_t fp = 0;
    is.read((char*)&fp, sizeof(fp));
    if (is.gcount() != static_cast<std::streamsize>(sizeof(fp))) {
        std::println(stderr, "error: model file is truncated (no tokenizer fingerprint trailer) -- retrain it");
        return false;
    }
    g_model_tok_fp = fp;
    // Trailing architecture fingerprint (see save_model) -- REQUIRED, same reasoning as the tokenizer
    // fingerprint above. The "absent implies un-looped" inference existed only to keep pre-LoopSplit
    // files loadable; nothing writes such files any more.
    std::uint64_t arch = 0;
    is.read((char*)&arch, sizeof(arch));
    if (is.gcount() != static_cast<std::streamsize>(sizeof(arch))) {
        std::println(stderr, "error: model file is truncated (no architecture trailer) -- retrain it");
        return false;
    }
    const std::uint64_t arch_got = arch;
    if (arch_got != ARCH_FINGERPRINT) {
        const ArchAxes got = arch_axes_of(arch_got);
        // A LOOP_REPEATS-ONLY difference is the single mismatch this path deliberately admits, and only
        // on this path. LoopSplit adds no parameters -- the middle block reuses the same weights and
        // PARAM_LAYOUT is keyed by layer INDEX, not execution -- so the blob is genuinely
        // interchangeable across repeat counts, and running a model at more (or fewer) passes than it
        // trained at is a real measurement rather than an accident: it is the standard evaluation for a
        // recurrent-depth architecture, and the direct test of whether a looped block learned an
        // ITERATIVE operator or a depth-specific pipeline. repeats=1 additionally runs a looped model
        // with the loop removed entirely.
        //
        // This mirrors the exemption layout.hpp's own axis rule already grants ROPE_SCALING
        // ("deliberately variable between train and inference"). It is scoped hard:
        //   * detected by substituting THIS build's repeats into the FILE's axes and requiring the
        //     result to reconstruct this build's fingerprint exactly -- so any second difference
        //     (middle_layers, rope_theta, depth-attn stride) still falls through to the refusal below;
        //   * TRAINING RESUME does not come through here. load_checkpoint (train_stage.cpp) keeps its
        //     hard refusal, because there a repeats mismatch is always a bug, never a measurement.
        const bool repeats_only =
            arch_fingerprint(got.middle_layers, LOOP_REPEATS, got.rope_theta, got.depth_attn_stride)
                == ARCH_FINGERPRINT;
        if (repeats_only) {
            std::println(stderr, "warning: model trained with LOOP_REPEATS {} is being run at {} "
                                 "({} executions here vs {} as trained). Weights are interchangeable "
                                 "(looping adds no parameters); this is a DIFFERENT COMPUTATION than "
                                 "the one that was trained, so treat the output as a loop-scaling "
                                 "measurement, not as this model's own quality.",
                         got.repeats, LOOP_REPEATS, sub0::LOOP_EXEC_COUNT,
                         N_LAYERS + LOOP_MIDDLE_LAYERS * (got.repeats - 1));
        } else {
        std::println(stderr, "error: model was built with a different architecture than this binary, "
                             "in a way shapes cannot show (the parameter blob is the same SIZE either way):");
        std::println(stderr, "  loop schedule : file {} middle layers x{} repeats | this build {} x{}",
                     got.middle_layers, got.repeats, LOOP_MIDDLE_LAYERS, LOOP_REPEATS);
        std::println(stderr, "  rope theta    : file {:g} | this build {:g}",
                     got.rope_theta, static_cast<double>(ROPE_THETA));
        std::println(stderr, "  depth attn    : file stride {} | this build stride {} (0 = off)",
                     got.depth_attn_stride, DEPTH_ATTN_STRIDE);
        std::println(stderr, "Rebuild with matching --loop-middle-layers/--loop-repeats/--rope-theta/"
                             "--depth-attn-stride.");
        return false;
        }
    }
    // Third trailing record (see save_model): the second architecture fingerprint word. UNLIKE the two
    // trailers above (both hard-required now, per their own comments), this one IS still tolerant of a
    // short/missing read -- it is brand new, so every file on disk today predates it, and "no trailer"
    // correctly means arch2 == 0 (no Gated DeltaNet), not "unknown, no guard" the way a genuinely
    // ambiguous legacy field would. A short-but-nonzero read (some bytes, not all 8) is real corruption,
    // not a legacy file, and is still rejected.
    std::uint64_t arch2 = 0;
    is.read((char*)&arch2, sizeof(arch2));
    const auto arch2_got = static_cast<std::streamsize>(is.gcount());
    if (arch2_got != 0 && arch2_got != static_cast<std::streamsize>(sizeof(arch2))) {
        std::println(stderr, "error: model file is truncated (partial architecture-v2 trailer) -- retrain it");
        return false;
    }
    if (arch2 != ARCH_FINGERPRINT2) {
        const ArchAxes2 got2 = arch_axes2_of(arch2);
        std::println(stderr, "error: model was built with a different Gated DeltaNet layer schedule, MoE "
                             "top-k and/or QSA indexer budget than this binary: file gdn full-attn stride "
                             "{} | this build stride {} (0 = off, the only value either side can currently "
                             "take -- docs/GATED_DELTANET.md); file experts-per-tok {} | this build {} "
                             "(0 = off -- docs/MOE.md); file qsa indexer budget/compress-ratio {}/{} | this "
                             "build {}/{} (0/0 = off -- docs/QSA.md).",
                     got2.gdn_full_attn_stride, GDN_FULL_ATTN_STRIDE,
                     got2.experts_per_tok, EXPERTS_PER_TOK,
                     got2.qsa_indexer_budget, got2.qsa_indexer_compress_ratio,
                     QSA_INDEXER_BUDGET, QSA_INDEXER_COMPRESS_RATIO);
        return false;
    }
    if (tok_model_conflict()) { warn_tok_model_mismatch(); return false; }
    // WP4e: a MOE_QUANT_EXPERTS build's weights are TWO files -- this blob and `<path>.moeq`, which
    // holds the routed experts in their native quantized bytes (include/sub0/moe_quant.hpp). The
    // sidecar is REQUIRED, not optional, in such a build: without it there are no routed experts at
    // all, and a forward pass would compute the shared expert alone and look plausible. Refusing here,
    // at the same seam that already refuses a config mismatch, is the "lowest callable seam" rule --
    // the alternative is discovering it inside op_moe, per token. A no-op returning true otherwise.
    if (!load_moe_quant_sidecar(path)) return false;
    return true;
}

const char* default_corpus()     { return DEFAULT_CORPUS; }
const char* default_corpus_tok() { return DEFAULT_CORPUS_TOK; }
const char* default_tokenizer()  { return DEFAULT_TOKENIZER; }

// ============================================================================
//  Runtime BPE tokenizer (loaded from tokenizer.tok) -- state declared up top
//  (g_tok) so save_model/load_model can fingerprint-guard the decoder/model pair.
// ============================================================================

std::uint64_t tokenizer_fingerprint() { return g_tok.loaded ? tok::fingerprint(g_tok) : 0; }
int eos_token_id() { return g_tok.loaded ? casing::TOK_EOS : -1; }

bool load_tokenizer(const char* path) {
    std::ifstream is(path, std::ios::binary);
    if (!is) { std::println(stderr, "tokenizer: cannot open '{}'", path); return false; }
    tok::Tokenizer t;
    if (!tok::deserialize(t, is)) { std::println(stderr, "tokenizer: bad or truncated '{}'", path); return false; }
    if (t.vocab != VOCAB)
        std::println(stderr, "tokenizer: vocab {} != built-in VOCAB {} (stale artifact?)", t.vocab, VOCAB);
    g_tok = std::move(t);
    // If a model is already loaded (gen loads the model first, then the tokenizer), refuse a decoder
    // that does not match the vocab those weights were trained against -- a loud, actionable failure
    // instead of silently detokenizing to garble.
    if (tok_model_conflict()) { warn_tok_model_mismatch(); g_tok = {}; return false; }
    return true;
}

std::vector<int> encode(const std::string& text) { return tok::encode(g_tok, text); }

std::string detokenize(const std::vector<int>& ids) { return tok::detokenize(g_tok, ids); }

namespace {
// Render a token's expansion (base-symbol codes) into a printable string: case
// markers become <|cap|>/<|up|>, control and high bytes are escaped, so the table
// stays one line per token regardless of the bytes a merge happens to contain.
std::string render_expansion(const std::vector<int>& codes) {
    std::string s;
    for (int code : codes) {
        if (code == casing::TOK_CAP)      { s += "<|cap|>"; continue; }
        if (code == casing::TOK_UP)       { s += "<|up|>";  continue; }
        if (code == casing::TOK_EOS)      { s += "<|endoftext|>"; continue; }
        // Any OTHER out-of-byte-range code is rendered explicitly rather than cast. Without this the
        // cast below silently wraps: TOK_EOS (256) became `\x00`, aliasing it onto the real NUL byte at
        // id 0 -- the exact distinction casing.hpp documents these two as having. `sub0llm vocab` showed
        // the end-of-text marker as an indistinguishable `byte \x00`, which is the table someone reads
        // FIRST when chasing a suspected tokenizer bug. Marker ids auto-increment from TOK_EOS, so a
        // future marker added without a case here degrades to a visible `<|?NNN|>` instead of aliasing
        // onto some unrelated byte.
        //
        // NOTE for the schemeV4 tokenizer merge (feature/tokenizer-v2, queued): V4 changes the marker
        // SET, so every marker it adds inherits exactly this trap. Keep this guard whatever ids V4
        // picks, give each new marker its own case + TokenEntry::Kind, and expect the regression test
        // "vocab: the EOS marker renders as itself..." (tests/engine_tests.cpp) to fail on the merge --
        // that failure is the checkpoint forcing a conscious decision per marker, not breakage.
        if (code < 0 || code > 0xFF) {
            char b[16];
            std::snprintf(b, sizeof b, "<|?%d|>", code);
            s += b;
            continue;
        }
        const unsigned char c = static_cast<unsigned char>(code);
        switch (c) {
            case '\n': s += "\\n"; break;
            case '\t': s += "\\t"; break;
            case '\r': s += "\\r"; break;
            default:
                if (c >= 0x20 && c < 0x7F) s += static_cast<char>(c);
                else { char b[5]; std::snprintf(b, sizeof b, "\\x%02X", c); s += b; }
        }
    }
    return s;
}
}  // namespace

std::vector<TokenEntry> vocab_entries() {
    std::vector<TokenEntry> rows;
    if (!g_tok.loaded) return rows;
    rows.reserve(g_tok.expansion.size());
    for (std::size_t id = 0; id < g_tok.expansion.size(); ++id) {
        const std::vector<int>& exp = g_tok.expansion[id];
        TokenEntry e;
        e.id = static_cast<int>(id);
        if (static_cast<int>(id) >= g_tok.n_base)        e.kind = TokenEntry::Kind::Merge;
        else if (!exp.empty() && exp[0] == casing::TOK_CAP) e.kind = TokenEntry::Kind::CapMarker;
        else if (!exp.empty() && exp[0] == casing::TOK_UP)  e.kind = TokenEntry::Kind::UpMarker;
        else if (!exp.empty() && exp[0] == casing::TOK_EOS) e.kind = TokenEntry::Kind::Eos;
        else                                                e.kind = TokenEntry::Kind::Byte;
        e.expansion_len = static_cast<int>(exp.size());
        e.text = render_expansion(exp);
        rows.push_back(std::move(e));
    }
    return rows;
}

int sample_token(const float* logits, float temp, int topk, std::mt19937& rng) {
    std::array<float, VOCAB> l;
    const float invT = 1.f / std::max(1e-6f, temp);
    for (int j = 0; j < VOCAB; ++j) l[j] = logits[j] * invT;
    if (topk > 0 && topk < VOCAB) {                       // keep only the top-k logits
        std::array<int, VOCAB> idx;
        for (int j = 0; j < VOCAB; ++j) idx[j] = j;
        std::partial_sort(idx.begin(), idx.begin() + topk, idx.end(),
                          [&](int a, int b) { return l[a] > l[b]; });
        std::array<float, VOCAB> keep;
        keep.fill(-1e30f);
        for (int t = 0; t < topk; ++t) keep[idx[t]] = l[idx[t]];
        l = keep;
    }
    float mx = -1e30f;
    for (float x : l) mx = std::max(mx, x);
    float Z = 0.f;
    for (float& x : l) { x = std::exp(x - mx); Z += x; }  // softmax (unnormalized; scale r by Z)
    std::uniform_real_distribution<float> ud(0.f, 1.f);
    float r = ud(rng) * Z, acc = 0.f;
    for (int j = 0; j < VOCAB; ++j) { acc += l[j]; if (r <= acc) return j; }
    return VOCAB - 1;
}

}  // namespace sub0
