# cmake/get_cpm.cmake — download CPM.cmake on first configure if not cached.
# Pin the version here; bump deliberately when updating.
set(CPM_DOWNLOAD_VERSION 0.40.2)
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
set(CPM_DOWNLOAD_SHA256 "C8CDC32C03816538CE22781ED72964DC864B2A34A310D3B7104812A5CA2D835D")
set(CPM_DOWNLOAD_TEMPORARY "${CPM_DOWNLOAD_LOCATION}.tmp")

if(NOT EXISTS "${CPM_DOWNLOAD_LOCATION}")
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/cmake")
  file(REMOVE "${CPM_DOWNLOAD_TEMPORARY}")
  message(STATUS "Downloading CPM.cmake v${CPM_DOWNLOAD_VERSION}...")
  file(DOWNLOAD
    "https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake"
    "${CPM_DOWNLOAD_TEMPORARY}"
    TIMEOUT 60
    EXPECTED_HASH "SHA256=${CPM_DOWNLOAD_SHA256}"
    STATUS CPM_DOWNLOAD_STATUS
    LOG CPM_DOWNLOAD_LOG
  )
  list(GET CPM_DOWNLOAD_STATUS 0 CPM_DOWNLOAD_CODE)
  if(NOT CPM_DOWNLOAD_CODE EQUAL 0)
    file(REMOVE "${CPM_DOWNLOAD_TEMPORARY}")
    message(FATAL_ERROR
      "Unable to download CPM.cmake v${CPM_DOWNLOAD_VERSION}: "
      "${CPM_DOWNLOAD_STATUS}\n${CPM_DOWNLOAD_LOG}")
  endif()
  file(RENAME "${CPM_DOWNLOAD_TEMPORARY}" "${CPM_DOWNLOAD_LOCATION}" RESULT CPM_RENAME_RESULT)
  if(NOT CPM_RENAME_RESULT STREQUAL "0")
    file(REMOVE "${CPM_DOWNLOAD_TEMPORARY}")
    message(FATAL_ERROR "Unable to cache CPM.cmake: ${CPM_RENAME_RESULT}")
  endif()
else()
  file(SHA256 "${CPM_DOWNLOAD_LOCATION}" CPM_CACHED_SHA256)
  if(NOT CPM_CACHED_SHA256 STREQUAL CPM_DOWNLOAD_SHA256)
    message(WARNING
      "Cached CPM.cmake v${CPM_DOWNLOAD_VERSION} has an unexpected SHA-256; removing it and retrying.")
    file(REMOVE "${CPM_DOWNLOAD_LOCATION}")
    include("${CMAKE_CURRENT_LIST_FILE}")
    return()
  endif()
endif()

include("${CPM_DOWNLOAD_LOCATION}")
