if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "SOURCE_DIR and OUTPUT_FILE are required")
endif()

execute_process(
  COMMAND git -C "${SOURCE_DIR}" rev-parse --short HEAD
  OUTPUT_VARIABLE SUB0_GIT_SHA
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET
  RESULT_VARIABLE GIT_RESULT)
if(NOT GIT_RESULT EQUAL 0 OR SUB0_GIT_SHA STREQUAL "")
  set(SUB0_GIT_SHA "nogit")
else()
  execute_process(
    COMMAND git -C "${SOURCE_DIR}" status --porcelain
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE STATUS_RESULT)
  if(NOT STATUS_RESULT EQUAL 0)
    set(SUB0_GIT_SHA "${SUB0_GIT_SHA}-unknown")
  elseif(NOT GIT_STATUS STREQUAL "")
    set(SUB0_GIT_SHA "${SUB0_GIT_SHA}-dirty")
  endif()
endif()

set(PROVENANCE_CONTENT "#pragma once\n#define SUB0_GIT_SHA \"${SUB0_GIT_SHA}\"\n")
set(WRITE_PROVENANCE TRUE)
if(EXISTS "${OUTPUT_FILE}")
  file(READ "${OUTPUT_FILE}" EXISTING_CONTENT)
  if(EXISTING_CONTENT STREQUAL PROVENANCE_CONTENT)
    set(WRITE_PROVENANCE FALSE)
  endif()
endif()
if(WRITE_PROVENANCE)
  file(WRITE "${OUTPUT_FILE}" "${PROVENANCE_CONTENT}")
endif()